countries_map_pt_en = {
    "Afeganistão": "Afghanistan",
    "África do Sul": "South Africa",
    "Albânia": "Albania",
    "Alemanha": "Germany",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antígua e Barbuda": "Antigua and Barbuda",
    "Arábia Saudita": "Saudi Arabia",
    "Argélia": "Algeria",
    "Argentina": "Argentina",
    "Armênia": "Armenia",
    "Austrália": "Australia",
    "Áustria": "Austria",
    "Azerbaijão": "Azerbaijan",
    "Bahamas": "Bahamas",
    "Bahrein": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Bielorrússia": "Belarus",
    "Bélgica": "Belgium",
    "Belize": "Belize",
    "Benin": "Benin",
    "Mianmar": "Myanmar",
    "Bolívia": "Bolivia",
    "Bósnia e Herzegovina": "Bosnia and Herzegovina",
    "Botsuana": "Botswana",
    "Brasil": "Brazil",
    "Brunei": "Brunei",
    "Bulgária": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Butão": "Bhutan",
    "Cabo Verde": "Cape Verde",
    "Camarões": "Cameroon",
    "Canadá": "Canada",
    "Cazaquistão": "Kazakhstan",
    "Chade": "Chad",
    "Chile": "Chile",
    "China": "China",
    "Chipre": "Cyprus",
    "Colômbia": "Colombia",
    "Comores": "Comoros",
    "República do Congo": "Republic of the Congo",
    "Costa Rica": "Costa Rica",
    "Croácia": "Croatia",
    "Cuba": "Cuba",
    "Chipre": "Cyprus",
    "Dinamarca": "Denmark",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "Egito": "Egypt",
    "El Salvador": "El Salvador",
    "Emirados Árabes Unidos": "United Arab Emirates",
    "Equador": "Ecuador",
    "Eritreia": "Eritrea",
    "Eslováquia": "Slovakia",
    "Eslovênia": "Slovenia",
    "Espanha": "Spain",
    "Estados Unidos": "United States",
    "Estônia": "Estonia",
    "Eswatini": "Eswatini",
    "Etiópia": "Ethiopia",
    "Fiji": "Fiji",
    "Filipinas": "Philippines",
    "Finlândia": "Finland",
    "França": "France",
    "Gabão": "Gabon",
    "Gâmbia": "Gambia",
    "Gana": "Ghana",
    "Grécia": "Greece",
    "Granada": "Grenada",
    "Guadalupe": "Guadeloupe",
    "Guatemala": "Guatemala",
    "Guiana": "Guyana",
    "Guiné": "Guinea",
    "Guiné-Bissau": "Guinea-Bissau",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hungria": "Hungary",
    "Iémen": "Yemen",
    "Ilhas Cook": "Cook Islands",
    "Ilhas Malvinas": "Falkland Islands",
    "Índia": "India",
    "Indonésia": "Indonesia",
    "Irã": "Iran",
    "Iraque": "Iraq",
    "Irlanda": "Ireland",
    "Islândia": "Iceland",
    "Israel": "Israel",
    "Itália": "Italy",
    "Jamaica": "Jamaica",
    "Japão": "Japan",
    "Jordânia": "Jordan",
    "Cazaquistão": "Kazakhstan",
    "Quênia": "Kenya",
    "Kiribati": "Kiribati",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Laos": "Laos",
    "Lesoto": "Lesotho",
    "Letônia": "Latvia",
    "Libéria": "Liberia",
    "Líbano": "Lebanon",
    "Libéria": "Liberia",
    "Lituânia": "Lithuania",
    "Luxemburgo": "Luxembourg",
    "Macedônia do Norte": "North Macedonia",
    "Madagascar": "Madagascar",
    "Malásia": "Malaysia",
    "Malawi": "Malawi",
    "Maldivas": "Maldives",
    "Mali": "Mali",
    "Malta": "Malta",
    "Marrocos": "Morocco",
    "Maurício": "Mauritius",
    "Mauritânia": "Mauritania",
    "México": "Mexico",
    "Micronésia": "Micronesia",
    "Moçambique": "Mozambique",
    "Moldávia": "Moldova",
    "Mônaco": "Monaco",
    "Mongólia": "Mongolia",
    "Montenegro": "Montenegro",
    "Namíbia": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Nicarágua": "Nicaragua",
    "Níger": "Niger",
    "Nigéria": "Nigeria",
    "Noruega": "Norway",
    "Nova Zelândia": "New Zealand",
    "Omã": "Oman",
    "Paquistão": "Pakistan",
    "Palau": "Palau",
    "Panamá": "Panama",
    "Papua-Nova Guiné": "Papua New Guinea",
    "Paraguai": "Paraguay",
    "Peru": "Peru",
    "Polônia": "Poland",
    "Portugal": "Portugal",
    "Quirguistão": "Kyrgyzstan",
    "República Centro-Africana": "Central African Republic",
    "República Tcheca": "Czech Republic",
    "República Democrática do Congo": "Democratic Republic of the Congo",
    "Romênia": "Romania",
    "Rússia": "Russia",
    "Ruanda": "Rwanda",
    "Saint Kitts e Nevis": "Saint Kitts and Nevis",
    "Saint Lucia": "Saint Lucia",
    "Saint Vincent e Grenadinas": "Saint Vincent and the Grenadines",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "Santo Tomé e Príncipe": "Sao Tome and Principe",
    "Senegal": "Senegal",
    "Serra Leoa": "Sierra Leone",
    "Singapura": "Singapore",
    "Síria": "Syria",
    "Somália": "Somalia",
    "Sri Lanka": "Sri Lanka",
    "Suazilândia": "Eswatini",
    "Sudão": "Sudan",
    "Sudão do Sul": "South Sudan",
    "Suriname": "Suriname",
    "Suécia": "Sweden",
    "Suíça": "Switzerland",
    "Sri Lanka": "Sri Lanka",
    "Tajiquistão": "Tajikistan",
    "Tanzânia": "Tanzania",
    "Timor-Leste": "Timor-Leste",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad e Tobago": "Trinidad and Tobago",
    "Tunísia": "Tunisia",
    "Turcomenistão": "Turkmenistan",
    "Turquia": "Turkey",
    "Tuvalu": "Tuvalu",
    "Uganda": "Uganda",
    "Ucrânia": "Ukraine",
    "Uruguai": "Uruguay",
    "Uzbequistão": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Vaticano": "Vatican City",
    "Venezuela": "Venezuela",
    "Vietnã": "Vietnam",
    "Iémen": "Yemen",
    "Zâmbia": "Zambia",
    "Zimbábue": "Zimbabwe",
    "Palestina": "Palestine",
    "Taiwan": "Taiwan",
    "Sahara Ocidental": "Western Sahara",
    "Kosovo": "Kosovo",
    "Ilhas Cook": "Cook Islands",
    "Liechtenstein": "Liechtenstein"
}
